inherit: 
    # - models_conf/mamba_tiny.yaml
    # - models_conf/mamba_small.yaml
    - models_conf/mamba_standard.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 101

training:
    seed: 0
    data: gaussian
    task_kwargs: {}
    data_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    learning_rate_schedule: cosine
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
